import type { Course, BlogPost, FAQItem, PricingPlan, Testimonial } from '@/types';

export const NAV_LINKS = [
  { label: 'Features', href: '/features' },
  { label: 'Pricing', href: '/pricing' },
  { label: 'Blog', href: '/blog' },
  { label: 'About', href: '/about' },
  { label: 'FAQ', href: '/faq' },
];

export const COURSES: Course[] = [
  {
    id: '1',
    title: 'Biodiversity Fundamentals',
    description: 'Explore the richness of life on Earth — from microbes to megafauna — and understand why biodiversity is the foundation of all ecosystems.',
    category: 'Biodiversity',
    level: 'beginner',
    duration: '6 weeks',
    enrolled: 12480,
    rating: 4.9,
    instructor: 'Dr. Priya Sharma',
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=600&auto=format&fit=crop&q=80',
    progress: 65,
  },
  {
    id: '2',
    title: 'Climate Change & Our Future',
    description: 'A deep dive into climate science, its global impacts, and actionable solutions for individuals and communities.',
    category: 'Climate',
    level: 'intermediate',
    duration: '8 weeks',
    enrolled: 18320,
    rating: 4.8,
    instructor: 'Prof. Arjun Mehta',
    image: 'https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?w=600&auto=format&fit=crop&q=80',
    progress: 30,
  },
  {
    id: '3',
    title: 'Wildlife Conservation Science',
    description: 'Learn the principles and practices of protecting endangered species and their habitats.',
    category: 'Wildlife',
    level: 'advanced',
    duration: '10 weeks',
    enrolled: 7650,
    rating: 4.9,
    instructor: 'Dr. Kavya Nair',
    image: 'https://images.unsplash.com/photo-1474511320723-9a56873867b5?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: '4',
    title: 'Sustainable Living Practices',
    description: 'Practical guides to reducing your carbon footprint and adopting an eco-friendly lifestyle.',
    category: 'Sustainability',
    level: 'beginner',
    duration: '4 weeks',
    enrolled: 25100,
    rating: 4.7,
    instructor: 'Meera Krishnan',
    image: 'https://images.unsplash.com/photo-1536147116438-62679a5e01f2?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: '5',
    title: 'Forest Ecology & Management',
    description: 'Understand forest ecosystems, their services, and evidence-based approaches to forest conservation.',
    category: 'Ecology',
    level: 'intermediate',
    duration: '7 weeks',
    enrolled: 9870,
    rating: 4.8,
    instructor: 'Dr. Rahul Verma',
    image: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: '6',
    title: 'Marine Conservation & Ocean Health',
    description: 'Dive into ocean ecosystems, coral reefs, marine biodiversity, and strategies to protect our seas.',
    category: 'Marine',
    level: 'intermediate',
    duration: '8 weeks',
    enrolled: 11200,
    rating: 4.9,
    instructor: 'Dr. Anjali Patel',
    image: 'https://images.unsplash.com/photo-1518020382113-a7e8fc38eac9?w=600&auto=format&fit=crop&q=80',
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: '1',
    title: 'The Silent Spring Revisited: How Chemical Pollution Threatens Pollinators',
    excerpt: 'Decades after Rachel Carson\'s warning, the crisis for bees, butterflies, and other pollinators has deepened. Here\'s what the latest research tells us.',
    content: '',
    author: 'Dr. Priya Sharma',
    category: 'Wildlife',
    tags: ['pollinators', 'pesticides', 'biodiversity'],
    publishedAt: '2026-05-20',
    readTime: '8 min read',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&auto=format&fit=crop&q=80',
    views: 14320,
  },
  {
    id: '2',
    title: 'India\'s Western Ghats: A Biodiversity Hotspot Under Pressure',
    excerpt: 'Home to over 5,000 flowering plant species and countless endemic animals, the Western Ghats face mounting threats from deforestation and development.',
    content: '',
    author: 'Prof. Arjun Mehta',
    category: 'Biodiversity',
    tags: ['india', 'western ghats', 'hotspot'],
    publishedAt: '2026-05-15',
    readTime: '10 min read',
    image: 'https://images.unsplash.com/photo-1542401886-65d6c61db217?w=800&auto=format&fit=crop&q=80',
    views: 9870,
  },
  {
    id: '3',
    title: 'Carbon Footprint 101: Simple Changes With Big Environmental Impact',
    excerpt: 'From diet to transport to energy use, here are evidence-based steps you can take today to dramatically reduce your personal carbon emissions.',
    content: '',
    author: 'Meera Krishnan',
    category: 'Sustainability',
    tags: ['carbon', 'climate action', 'lifestyle'],
    publishedAt: '2026-05-10',
    readTime: '6 min read',
    image: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800&auto=format&fit=crop&q=80',
    views: 22450,
  },
  {
    id: '4',
    title: 'AI in Conservation: How Machine Learning Is Protecting Wildlife',
    excerpt: 'Camera traps, acoustic monitoring, satellite imagery — discover how AI tools are revolutionizing the way we detect, track, and protect endangered species.',
    content: '',
    author: 'Dr. Kavya Nair',
    category: 'Technology',
    tags: ['AI', 'conservation', 'technology'],
    publishedAt: '2026-05-05',
    readTime: '9 min read',
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop&q=80',
    views: 18900,
  },
  {
    id: '5',
    title: 'Rewilding Europe: Returning Nature to Its Former Glory',
    excerpt: 'Across the continent, ambitious projects are reintroducing wolves, bison, and lynx to restore ecosystems that were devastated over centuries.',
    content: '',
    author: 'Dr. Rahul Verma',
    category: 'Conservation',
    tags: ['rewilding', 'europe', 'restoration'],
    publishedAt: '2026-04-28',
    readTime: '11 min read',
    image: 'https://images.unsplash.com/photo-1534567153574-2b12153a87f0?w=800&auto=format&fit=crop&q=80',
    views: 12300,
  },
  {
    id: '6',
    title: 'The Ocean Plastic Crisis: Progress, Challenges, and Solutions',
    excerpt: 'An estimated 14 million tons of plastic enter our oceans each year. We examine what\'s working, what\'s not, and what needs to change.',
    content: '',
    author: 'Dr. Anjali Patel',
    category: 'Marine',
    tags: ['ocean', 'plastic', 'pollution'],
    publishedAt: '2026-04-22',
    readTime: '7 min read',
    image: 'https://images.unsplash.com/photo-1559825481-12a05cc00344?w=800&auto=format&fit=crop&q=80',
    views: 16780,
  },
];

export const FAQ_ITEMS: FAQItem[] = [
  {
    id: '1',
    question: 'What is NatureGyan and who is it for?',
    answer: 'NatureGyan is an AI-powered environmental education platform designed for students, teachers, researchers, nature enthusiasts, and conservation organizations. Whether you are a school student learning about ecosystems or a professional researcher studying biodiversity, NatureGyan offers tailored learning experiences.',
    category: 'General',
  },
  {
    id: '2',
    question: 'Are the courses certified?',
    answer: 'Yes! Most courses on NatureGyan offer verified certificates upon completion. Our Professional and Enterprise plans include certificates recognized by partner organizations and educational institutions. Certificates can be downloaded, shared on LinkedIn, and added to your portfolio.',
    category: 'Courses',
  },
  {
    id: '3',
    question: 'How does the AI Nature Assistant work?',
    answer: 'Our AI Nature Assistant is powered by state-of-the-art language models fine-tuned on environmental science data. You can ask it questions about wildlife, plants, ecosystems, climate science, and conservation. It also assists with species identification when you upload photos.',
    category: 'AI Features',
  },
  {
    id: '4',
    question: 'Can I use NatureGyan for free?',
    answer: 'Absolutely! Our Explorer plan is completely free and gives you access to foundational courses, basic AI assistance, community forums, and selected resources. You can upgrade to a paid plan anytime to unlock advanced features, full course libraries, and premium tools.',
    category: 'Pricing',
  },
  {
    id: '5',
    question: 'How does the species identification feature work?',
    answer: 'Simply upload a clear photo of a plant, bird, insect, or animal using our AI Identifier tool. Our computer vision models will analyze the image and provide species information, habitat details, conservation status, and related learning resources — all in seconds.',
    category: 'AI Features',
  },
  {
    id: '6',
    question: 'Is NatureGyan available on mobile?',
    answer: 'Yes! NatureGyan is fully responsive and works beautifully on all devices. We also offer progressive web app (PWA) support so you can install it on your home screen for an app-like experience without needing to download from an app store.',
    category: 'General',
  },
  {
    id: '7',
    question: 'Can teachers create and manage classes?',
    answer: 'Yes, educators can create virtual classrooms, enroll students, assign courses and challenges, track individual progress, and communicate with learners. Our Professional plan includes full classroom management tools with detailed analytics.',
    category: 'Education',
  },
  {
    id: '8',
    question: 'What is the Carbon Footprint Calculator?',
    answer: 'Our Carbon Footprint Calculator helps you estimate your personal environmental impact based on your diet, transportation, energy consumption, and shopping habits. It then provides personalized recommendations to help you reduce your footprint and track your progress over time.',
    category: 'Features',
  },
  {
    id: '9',
    question: 'How do I join eco-challenges and campaigns?',
    answer: 'From your dashboard, navigate to the "Challenges" section to browse active eco-challenges like tree planting drives, cleanup campaigns, and sustainability quests. Join any challenge, log your activities, upload proof, and earn eco-points and badges.',
    category: 'Community',
  },
  {
    id: '10',
    question: 'Do you offer discounts for educational institutions?',
    answer: 'Yes! We offer significant discounts for schools, universities, and NGOs. Our Enterprise plan includes custom pricing for bulk licenses, dedicated support, white-labeling options, and institution-wide analytics. Contact us for a custom quote.',
    category: 'Pricing',
  },
];

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: 'explorer',
    name: 'Explorer',
    price: { monthly: 0, yearly: 0 },
    description: 'Perfect for curious learners starting their nature education journey.',
    features: [
      'Access to 20+ foundational courses',
      'Basic AI Nature Assistant',
      'Community forum access',
      'Wildlife encyclopedia',
      'Monthly nature newsletter',
      'Mobile-friendly learning',
    ],
    highlighted: false,
    cta: 'Start Free',
  },
  {
    id: 'naturalist',
    name: 'Naturalist',
    price: { monthly: 12, yearly: 99 },
    description: 'For dedicated learners who want full access to courses and AI tools.',
    features: [
      'Everything in Explorer',
      'Access to 200+ advanced courses',
      'Full AI Nature Assistant',
      'AI Plant & Animal Identifier',
      'Verified course certificates',
      'Carbon footprint calculator',
      'Eco-challenge participation',
      'Research repository access',
      'Priority support',
    ],
    highlighted: true,
    cta: 'Start 14-Day Trial',
  },
  {
    id: 'professional',
    name: 'Professional',
    price: { monthly: 29, yearly: 249 },
    description: 'For educators, researchers, and organizations driving real impact.',
    features: [
      'Everything in Naturalist',
      'Classroom management tools',
      'Student progress analytics',
      'Research publication tools',
      'Event & workshop creation',
      'Eco-project management',
      'Custom learning paths',
      'Volunteer network access',
      'API access',
      'Dedicated account manager',
    ],
    highlighted: false,
    cta: 'Start 14-Day Trial',
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'Ananya Krishnamurthy',
    role: 'Biology Teacher',
    organization: 'Delhi Public School',
    content: 'NatureGyan has transformed how I teach environmental science. My students are genuinely excited about ecology and biodiversity now. The AI tools make concepts tangible and the courses are beautifully structured.',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1777471369951-681215f15a71?q=80&w=1165&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    id: '2',
    name: 'Dr. Suresh Iyer',
    role: 'Wildlife Researcher',
    organization: 'Wildlife Institute of India',
    content: 'The research repository and AI assistant are exceptional. I use NatureGyan to access case studies, collaborate with the community, and share my findings with a broader audience. Highly recommended for researchers.',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&auto=format&fit=crop&q=80',
  },
  {
    id: '3',
    name: 'Riya Desai',
    role: 'Class 11 Student',
    organization: 'Mumbai',
    content: 'I identified 15 bird species in my garden using the AI identifier — and then enrolled in the Bird Watching course to learn more about each one. NatureGyan makes learning feel like an adventure.',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&auto=format&fit=crop&q=80',
  },
  {
    id: '4',
    name: 'Vikram Nair',
    role: 'NGO Director',
    organization: 'Green Earth Foundation',
    content: 'We use NatureGyan\'s Professional plan to manage our volunteer programs and track environmental impact. The analytics dashboard is powerful and the community features help us reach passionate supporters.',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
  },
  {
    id: '5',
    name: 'Preethi Sundar',
    role: 'Environmental Consultant',
    organization: 'Sustainable Futures',
    content: 'The carbon footprint calculator and sustainability hub are excellent resources for my consulting work. I regularly recommend NatureGyan to clients who want to build environmental literacy in their teams.',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&auto=format&fit=crop&q=80',
  },
  {
    id: '6',
    name: 'Karthik Murugan',
    role: 'Nature Photographer',
    organization: 'Freelance',
    content: 'The species identification tool is incredible — it identified a rare moth I photographed in Coorg within seconds. NatureGyan bridges the gap between citizen science and professional research beautifully.',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
  },
];

export const STATS = [
  { value: '2.4M+', label: 'Active Learners', icon: 'Users' },
  { value: '500+', label: 'Expert Courses', icon: 'BookOpen' },
  { value: '180+', label: 'Countries Reached', icon: 'Globe' },
  { value: '94%', label: 'Satisfaction Rate', icon: 'Star' },
];

export const FEATURES_LIST = [
  {
    icon: 'Brain',
    title: 'AI Nature Assistant',
    description: 'Ask anything about wildlife, plants, ecosystems, or climate. Get instant, science-backed answers from our specialized AI.',
    color: 'green',
  },
  {
    icon: 'Camera',
    title: 'Species Identification',
    description: 'Upload a photo of any plant, bird, or insect and get instant AI-powered identification with detailed species information.',
    color: 'blue',
  },
  {
    icon: 'GraduationCap',
    title: 'Nature Learning Academy',
    description: '500+ courses on biodiversity, climate change, wildlife, sustainability, and ecology — taught by world-class experts.',
    color: 'brown',
  },
  {
    icon: 'Globe',
    title: 'Biodiversity Explorer',
    description: 'Explore interactive maps and encyclopedias of flora and fauna, habitat types, and conservation status worldwide.',
    color: 'green',
  },
  {
    icon: 'Leaf',
    title: 'Sustainability Hub',
    description: 'Carbon footprint calculator, eco-challenges, green living guides, and personal sustainability tracking.',
    color: 'blue',
  },
  {
    icon: 'Users',
    title: 'Eco-Community Network',
    description: 'Connect with naturalists, researchers, and conservationists. Join forums, citizen science projects, and local eco-clubs.',
    color: 'brown',
  },
  {
    icon: 'Trophy',
    title: 'Eco-Challenges & Campaigns',
    description: 'Participate in tree planting drives, cleanup campaigns, wildlife monitoring, and sustainability challenges.',
    color: 'green',
  },
  {
    icon: 'BarChart3',
    title: 'Impact Dashboard',
    description: 'Track your learning progress, sustainability score, carbon reduction, eco-activities, and achievement badges.',
    color: 'blue',
  },
  {
    icon: 'BookOpen',
    title: 'Research Repository',
    description: 'Access thousands of research papers, environmental reports, case studies, and scientific publications.',
    color: 'brown',
  },
];

export const WORKFLOW_STEPS = [
  {
    step: '01',
    title: 'Create Your Learning Profile',
    description: 'Tell us your interests — biodiversity, climate, wildlife, or sustainability. Our AI personalizes your learning journey from day one.',
    icon: 'UserCircle',
  },
  {
    step: '02',
    title: 'Explore & Learn',
    description: 'Dive into expert-crafted courses, use the AI assistant to answer your questions, and explore the biodiversity encyclopedia.',
    icon: 'Search',
  },
  {
    step: '03',
    title: 'Identify & Discover',
    description: 'Upload photos to identify species in your surroundings. Every identification becomes a learning moment linked to relevant courses.',
    icon: 'Scan',
  },
  {
    step: '04',
    title: 'Act & Make Impact',
    description: 'Join eco-challenges, participate in campaigns, reduce your carbon footprint, and contribute to citizen science projects.',
    icon: 'Zap',
  },
];
